# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./config_api
# Target is a library:  

SOURCES += config_api.c \
           find.c \
           utils.c 
HEADERS += config_api.h \
           find.h \
           utils.h 
TEMPLATE = lib 
CONFIG = release \
         warn_on \
         staticlib 
