# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

INSTALLS += target
SUBDIRS += config_api \
           console \
           src 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
