# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./console
# Target is an application:  ../bin/feraser

INSTALLS += target
SOURCES += main.cpp 
HEADERS += feraser.h \
           filelib.h 
TEMPLATE = app 
CONFIG = release \
         warn_on 
TARGET = ../bin/feraser 
